name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to use for tests (chromium, firefox)'
        required: true
        default: 'chromium'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: change working directory to Task_1.2
        run: cd Task_1.2
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:ci:${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
